version: "2.3"
services:
  monstache:
    image: rwynn/monstache:6.7.14
    container_name: search_monstache_${COMPOSE_PROJECT_NAME}
    working_dir: /app
    command: -f /app/monstache.config.toml
    volumes:
      - ${MONSTACHE_DIR}/${TOML_FILENAME}:/app/monstache.config.toml
      - ${MONSTACHE_DIR}/logs:${MONSTACHE_DIR}/logs
    ports:
      - "${MONSTACHE_PORT}:8080"
    healthcheck:
      test: "wget -q -O - http://localhost:8080/healthz"
      interval: 10s
      timeout: 30s
      retries: 300
    restart: unless-stopped
    
networks:
  default:
    name: dev_network
    external: true
    